from uix.navbar import NavBar
from uix.navicon import NavIcon
from uix.snapscroll import SnapScroll
from uix.snapscroll_h import SnapScrollH
from uix.videocard import VideoCard
from uix.profileimage import ProfileImg
from uix.albumimage import AlbumImg
from uix.matchcard import MatchCard
#from uix.myswiper import MySwiper